- name: "Copy lb-health-check.html file"
  copy: src=files/lb-health-check.html dest=/var/www/html/lb-health-check.html

- name: "Copy httpd Configuration file"
  copy:
    src: files/httpd.original
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
  - restart apache

