- name: play1
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3  
  tasks:
    - name: List keys simple
      aws_s3:
        object: SampleWebApp123.war
        bucket: artifactory-09apr2020
        dest: /tmp/SampleWebApp123.war
        mode: get

